export const BOOKLIST_REQUESTED = "BOOKLIST_REQUESTED";
export const BOOKLIST_SUCEEDED = "BOOKLIST_SUCEEDED";
export const BOOKLIST_FAILED = "BOOKLIST_FAILED";

export const GET_LATEST_BOOK_REQUEST = "GET_LATEST_BOOK_REQUEST";
export const GET_LATEST_BOOK_SUCCESS = "GET_LATEST_BOOK_SUCCESS";
export const GET_LATEST_BOOK_FAILED = "GET_LATEST_BOOK_FAILED";
