export const ADD_PAYMENT_INFO = "ADD_PAYMENT_INFO";

export const PAYMENT_INTENT_REQUEST = "PAYMENT_INTENT_REQUEST";
export const PAYMENT_INTENT_SUCCESS = "PAYMENT_INTENT_SUCCESS";
export const PAYMENT_INTENT_FAILED = "PAYMENT_INTENT_FAILED";

export const CLEAR_PAYMENT_INFO = "CLEAR_PAYMENT_INFO";
